# Emits the standalone preflight-denso.sh guard.
#
# `denso-setup preflight` (packaging/denso-setup cmd_preflight) cannot protect
# a FIRST install: denso-setup does not exist on the box until the .deb
# containing it is already installed, so by the time it could run, the
# transaction it would veto has already happened. build_package.sh therefore
# also emits this standalone twin next to the .deb.
#
# GENERATED, never hand-copied: this is the ONE place that assembles the
# standalone script, called by both build_package.sh (the real artifact) and
# tests/packaging/run.sh (which proves it and `apt_plan_ok` never disagree). A
# hand-copy would drift from packaging/lib/policy.sh; a second copy of this
# emitter would let the two callers' generated scripts drift from EACH OTHER.
# Concatenation, not sourcing, because the standalone script must run on a box
# where /opt/denso does not exist yet — it carries its own copy of policy.sh's
# functions inline.
#
# POSIX sh, sourceable by build_package.sh (bash) and run.sh (bash) alike.
# A subshell body ( ... ), not { ... }: POSIX shell variables are global by
# default, so a brace-bodied function's locals (policy/out/tmp here) would
# clobber a caller's variables of the same name — the exact defect already
# fixed across every function in packaging/lib/policy.sh. A subshell still
# writes $out to disk and propagates the exit status; only the assignments
# stay contained.
#
#   emit_preflight_script <path-to-policy.sh> <output-path> <expected-deb-sha256>
emit_preflight_script() (
    policy="$1"; out="$2"; deb_sha="$3"
    # Write to a temp file in the SAME directory as $out (so the final `mv` is
    # a same-filesystem rename), chmod it, THEN move it into place. A
    # generator failure partway through the heredoc below must never leave a
    # partial-but-executable $out sitting where an operator might run it.
    tmp="$(mktemp "$(dirname "$out")/.preflight-denso.XXXXXX")" || return 1
    {
        echo '#!/bin/sh'
        echo '# GENERATED by build_package.sh via packaging/lib/gen_preflight.sh — do not'
        echo '# hand-edit; regenerate by rebuilding the .deb. This concatenates'
        echo '# packaging/lib/policy.sh verbatim so this standalone guard and'
        echo '# `denso-setup preflight` can never silently diverge.'
        echo 'set -eu'
        echo 'LC_ALL=C'
        echo 'export LC_ALL'
        # Binds this guard to the ONE .deb it was generated for. Every build
        # used to overwrite the same preflight-denso.sh filename, so an
        # operator could pair an OLD guard with a NEW .deb with no error at
        # all -- this embedded checksum is what makes that pairing mistake
        # fail loudly instead of silently "passing" a stale review.
        printf 'EXPECTED_DEB_SHA256=%s\n' "$deb_sha"
        cat "$policy"
        cat <<'DRIVER'

# --- driver ---------------------------------------------------------------
# Runs BEFORE denso-setup exists on the box (it ships inside the .deb this
# guards), so a first install has no other veto point than this file.
die() { echo "preflight-denso: $*" >&2; exit 1; }
[ "$(id -u)" = "0" ] || die "must run as root (sudo ./preflight-denso.sh <deb>)"
deb="${1-}"; [ -f "$deb" ] || die "usage: $0 <path-to.deb>"

# Refuse a mismatched .deb BEFORE simulating apt: the hash check must precede
# the simulation, or a stale guard could still "usefully" vet the wrong
# artifact and print a false PASS for a .deb it never actually inspected.
actual_deb_sha="$(sha256sum "$deb" | cut -d' ' -f1)"
[ "$actual_deb_sha" = "$EXPECTED_DEB_SHA256" ] || \
    die "refusing: '$deb' (sha256 $actual_deb_sha) is not the .deb this preflight script was generated for (expected $EXPECTED_DEB_SHA256) -- use the preflight-denso-<version>.sh that shipped beside THIS .deb"

plan="$(mktemp)"
trap 'rm -f "$plan"' EXIT

# No `|| true`: a simulation that fails to run is NOT a safe empty plan.
# apt needs a PATH, not a bare name: `apt-get install foo.deb` treats foo.deb as
# a PACKAGE NAME and fails with "Unable to locate package foo.deb". Only an
# argument containing a slash is read as a local file. Normalise to an absolute
# path so the operator can pass `x.deb`, `./x.deb` or a full path and get the
# same behaviour -- and so the command we PRINT is one that actually works.
deb="$(cd "$(dirname "$deb")" && pwd)/$(basename "$deb")"
if ! LC_ALL=C apt-get -s install --no-install-recommends "$deb" > "$plan" 2>&1; then
    echo "preflight-denso: apt simulation FAILED — refusing:" >&2
    cat "$plan" >&2
    exit 1
fi

if apt_plan_ok "$plan"; then
    echo "preflight-denso: PASS — installing this package would not touch a protected JetPack package"
    # Same options as the simulation above -- --no-install-recommends changes
    # the transaction apt plans, so printing a different invocation here would
    # tell the operator to run something we never actually vetted.
    echo "preflight-denso: now run:  sudo apt install --no-install-recommends $deb"
    exit 0
fi
exit 1
DRIVER
    } > "$tmp" || { rm -f "$tmp"; return 1; }
    chmod +x "$tmp" || { rm -f "$tmp"; return 1; }
    mv -f "$tmp" "$out" || { rm -f "$tmp"; return 1; }
)
