# Emits the standalone preflight-denso.sh guard.
#
# `denso-setup preflight` (packaging/denso-setup cmd_preflight) cannot protect
# a FIRST install: denso-setup does not exist on the box until the .deb
# containing it is already installed, so by the time it could run, the
# transaction it would veto has already happened. build_package.sh therefore
# also emits this standalone twin next to the .deb.
#
# GENERATED, never hand-copied: this is the ONE place that assembles the
# standalone script, called by both build_package.sh (the real artifact) and
# tests/packaging/run.sh (which proves it and `apt_plan_ok` never disagree). A
# hand-copy would drift from packaging/lib/policy.sh; a second copy of this
# emitter would let the two callers' generated scripts drift from EACH OTHER.
# Concatenation, not sourcing, because the standalone script must run on a box
# where /opt/denso does not exist yet — it carries its own copy of policy.sh's
# functions inline.
#
# POSIX sh, sourceable by build_package.sh (bash) and run.sh (bash) alike.
#
#   emit_preflight_script <path-to-policy.sh> <output-path>
emit_preflight_script() {
    policy="$1"; out="$2"
    {
        echo '#!/bin/sh'
        echo '# GENERATED by build_package.sh via packaging/lib/gen_preflight.sh — do not'
        echo '# hand-edit; regenerate by rebuilding the .deb. This concatenates'
        echo '# packaging/lib/policy.sh verbatim so this standalone guard and'
        echo '# `denso-setup preflight` can never silently diverge.'
        echo 'set -eu'
        echo 'LC_ALL=C'
        echo 'export LC_ALL'
        cat "$policy"
        cat <<'DRIVER'

# --- driver ---------------------------------------------------------------
# Runs BEFORE denso-setup exists on the box (it ships inside the .deb this
# guards), so a first install has no other veto point than this file.
die() { echo "preflight-denso: $*" >&2; exit 1; }
[ "$(id -u)" = "0" ] || die "must run as root (sudo ./preflight-denso.sh <deb>)"
deb="${1-}"; [ -f "$deb" ] || die "usage: $0 <path-to.deb>"

plan="$(mktemp)"
trap 'rm -f "$plan"' EXIT

# No `|| true`: a simulation that fails to run is NOT a safe empty plan.
if ! LC_ALL=C apt-get -s install --no-install-recommends "$deb" > "$plan" 2>&1; then
    echo "preflight-denso: apt simulation FAILED — refusing:" >&2
    cat "$plan" >&2
    exit 1
fi

if apt_plan_ok "$plan"; then
    echo "preflight-denso: PASS — installing this package would not touch a protected JetPack package"
    # Same options as the simulation above -- --no-install-recommends changes
    # the transaction apt plans, so printing a different invocation here would
    # tell the operator to run something we never actually vetted.
    echo "preflight-denso: now run:  sudo apt install --no-install-recommends $deb"
    exit 0
fi
exit 1
DRIVER
    } > "$out"
    chmod +x "$out"
}
